services:
  zscore-mariadb:
    build: .
    container_name: zscore-mariaDB
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - backend_network

volumes:
  mariadb_data:
    driver: local

networks:
  backend_network:
    driver: bridge

