services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./volume:/var/lib/mysql
    networks:
      - backend_network

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_ROOT_PASSWORD: ${DB_ROOTPASSWORD}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      PHP_MAX_RETRIES: 10
      PHP_RETRY_DELAY: 3
    networks:
      - backend_network

volumes:
  mariadb_data:
    driver: local

networks:
  backend_network:
    driver: bridge

