version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: zscoredb
    ports:
      - "3306:3306"
    volumes:
      - ./volume:/var/lib/mysql

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    environment:
      PHP_MAX_RETRIES: 10
      PHP_RETRY_DELAY: 3

volumes:
  mariadb_data:
    driver: local
