services:
  php:
    build: .
    container_name: api
    environment:
      DB_HOST: mariadb
      DB_ROOT_PASSWORD: rootpassword
      DB_NAME: zscoredb
      DB_USER: user
      DB_PASSWORD: password
    volumes:
      - ./src:/var/www/html
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
